### ISSUE TITLE
Cannot pip install agatestats

### ISSUE THREAD

**Issue by sfrostenson** [wireservice/agate-stats#15]
For both python 2.7 and python 3.5

`Collecting agatestats
  Could not find a version that satisfies the requirement agatestats (from versions: )
No matching distribution found for agatestats`

**Comment by esagara** [comment]
Try `pip install agate-stats`

**Comment by onyxfish** [comment]
Yep, I know this is confusing, but I'm not sure what to do about it. Conventions are simply different for package names versus module names. 😢
